# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MHacks19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MHacks19

  target 'MHacks19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MHacks19UITests' do
    # Pods for testing
  end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
